# metamodel_version: 1.11.0# version: 1.2.1id: AssessmentResultsLocalDefinitions
schema_generating: true
description: Used to define data objects that are referenced by the assessment results
  but do not appear in the imported assessment plan.
display_name: AssessmentResultsLocalDefinitions
document_category: AssessmentResultsLocalDefinitions
weight: 20
fields:
- id: objectives_and_methods
  description: A collection of locally-defined control objectives.
  display_name: objectives-and-methods
  cardinality: multi
- id: activities
  description: A collection of activities.
  display_name: activities
  cardinality: multi
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
