# metamodel_version: 1.11.0# version: 1.2.1id: Base64Resource
schema_generating: true
description: A resource encoded using the Base64 alphabet defined by RFC 2045.
display_name: Base64Resource
document_category: Base64Resource
weight: 20
fields:
- id: media_type
  description: A label that indicates the nature of a resource, as a data serialization
    or format.
  display_name: media-type
- id: value
  description: The value associated with the containing object.
  display_name: Base64Resource_value
- id: filename
  description: Name of the file before it was encoded as Base64 to be embedded in
    a resource.
  display_name: filename
