# metamodel_version: 1.11.0# version: 1.2.1id: ComponentStatus
schema_generating: true
description: Describes the operational status of the system component.
display_name: ComponentStatus
document_category: ComponentStatus
weight: 20
fields:
- id: state
  description: The operational status.
  display_name: ComponentStatus_state
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
