# metamodel_version: 1.11.0# version: 1.2.1id: Facet
schema_generating: true
description: An individual characteristic that is part of a larger set produced by
  the same actor.
display_name: Facet
document_category: Facet
weight: 20
fields:
- id: name
  description: A textual label that uniquely identifies an attribute or semantic type.
  display_name: Facet_name
- id: value
  description: The value associated with the containing object.
  display_name: Facet_value
- id: system
  description: Specifies the system or scheme from which the identifier originates.
  display_name: Facet_system
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
- id: props
  description: A list of properties.
  display_name: props
  cardinality: multi
- id: links
  description: A list of links.
  display_name: links
  cardinality: multi
