# metamodel_version: 1.11.0# version: 1.2.1id: IncorporatesComponent
schema_generating: true
description: The collection of components comprising a capability.
display_name: IncorporatesComponent
document_category: IncorporatesComponent
weight: 20
fields:
- id: component_uuid
  description: A UUID reference to a component.
  display_name: IncorporatesComponent_component-uuid
- id: description
  description: A human-readable description.
  display_name: IncorporatesComponent_description
