# metamodel_version: 1.11.0# version: 1.2.1id: LeveragedAuthorization
schema_generating: true
description: A description of another authorized system from which this system inherits
  capabilities that satisfy security requirements. Another term for this concept is
  a common control provider.
display_name: LeveragedAuthorization
document_category: LeveragedAuthorization
weight: 20
fields:
- id: uuid
  description: A machine-oriented, globally unique identifier with a cross-instance
    scope.
  display_name: LeveragedAuthorization_uuid
- id: title
  description: A human-readable name or title.
  display_name: LeveragedAuthorization_title
- id: props
  description: A list of properties.
  display_name: props
  cardinality: multi
- id: links
  description: A list of links.
  display_name: LeveragedAuthorization_links
  cardinality: multi
- id: party_uuid
  description: A machine-oriented identifier reference to the party who is making
    the log entry.
  display_name: LeveragedAuthorization_party-uuid
- id: date_authorized
  description: The date the system received its authorization.
  display_name: LeveragedAuthorization_date-authorized
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
