# metamodel_version: 1.11.0# version: 1.2.1id: NetworkArchitecture
schema_generating: true
description: A description of the system's network architecture, optionally supplemented
  with diagrams that illustrate the network architecture.
display_name: NetworkArchitecture
document_category: NetworkArchitecture
weight: 20
fields:
- id: description
  description: A human-readable description.
  display_name: NetworkArchitecture_description
- id: props
  description: A list of properties.
  display_name: props
  cardinality: multi
- id: links
  description: A list of links.
  display_name: links
  cardinality: multi
- id: diagrams
  description: A collection of diagrams that visually depict the subject.
  display_name: diagrams
  cardinality: multi
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
