# metamodel_version: 1.11.0# version: 1.2.1id: PlanOfActionAndMilestones
schema_generating: true
description: A plan of action and milestones that identifies initial and residual
  risks, deviations, and disposition.
display_name: PlanOfActionAndMilestones
document_category: PlanOfActionAndMilestones
weight: 20
fields:
- id: uuid
  description: A machine-oriented, globally unique identifier with a cross-instance
    scope.
  display_name: PlanOfActionAndMilestones_uuid
- id: metadata
  description: Provides information about the containing document, and defines concepts
    shared across the document.
  display_name: PlanOfActionAndMilestones_metadata
- id: import_ssp
  description: Used to import information about the system from an SSP.
  display_name: import-ssp
- id: system_id
  description: A human-oriented, globally unique identifier for a system.
  display_name: system-id
- id: local_definitions
  description: Used to define data objects that do not appear in the referenced SSP.
  display_name: PlanOfActionAndMilestones_local-definitions
- id: observations
  description: A collection of observations captured in the containing context.
  display_name: observations
  cardinality: multi
- id: risks
  description: A collection of risks captured in the containing context.
  display_name: risks
  cardinality: multi
- id: findings
  description: A collection of findings captured in the containing context.
  display_name: findings
  cardinality: multi
- id: poam_items
  description: A collection of POA&M items.
  display_name: PlanOfActionAndMilestones_poam-items
  cardinality: multi
- id: back_matter
  description: A collection of resources that may be referenced from within the OSCAL
    document instance.
  display_name: back-matter
