# metamodel_version: 1.11.0# version: 1.2.1id: PoamItem
schema_generating: true
description: Describes an individual POA&M item.
display_name: PoamItem
document_category: PoamItem
weight: 20
fields:
- id: uuid
  description: A machine-oriented, globally unique identifier with a cross-instance
    scope.
  display_name: uuid
- id: title
  description: A human-readable name or title.
  display_name: PoamItem_title
- id: description
  description: A human-readable description.
  display_name: PoamItem_description
- id: origins
  description: Identifies the source of observations, findings, or risks.
  display_name: origins
  cardinality: multi
- id: related_findings
  description: Relates a POA&M item to one or more findings.
  display_name: related-findings
  cardinality: multi
- id: related_observations
  description: Relates the containing object to a set of referenced observations.
  display_name: related-observations
  cardinality: multi
- id: related_risks
  description: Relates the finding to a set of referenced risks.
  display_name: related-risks
  cardinality: multi
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
- id: props
  description: A list of properties.
  display_name: props
  cardinality: multi
- id: links
  description: A list of links.
  display_name: links
  cardinality: multi
