# metamodel_version: 1.11.0# version: 1.2.1id: RelevantEvidence
schema_generating: true
description: Links this observation to relevant evidence.
display_name: RelevantEvidence
document_category: RelevantEvidence
weight: 20
fields:
- id: href
  description: A resolvable URL reference to a resource.
  display_name: href
- id: description
  description: A human-readable description.
  display_name: RelevantEvidence_description
- id: remarks
  description: Additional commentary about the containing object.
  display_name: remarks
- id: props
  description: A list of properties.
  display_name: props
  cardinality: multi
- id: links
  description: A list of links.
  display_name: links
  cardinality: multi
