# metamodel_version: 1.11.0# version: 1.2.1id: TermsAndConditionsPart
schema_generating: true
description: A terms-and-conditions scoped assessment part.
display_name: TermsAndConditionsPart
document_category: TermsAndConditionsPart
weight: 20
fields:
- id: uuid
  description: A machine-oriented, globally unique identifier with a cross-instance
    scope.
  display_name: uuid
- id: ns
  description: An optional namespace qualifying a name. Allows different organizations
    to associate distinct semantics with the same name.
  display_name: ns
- id: _class
  description: A textual label that provides a sub-type or characterization.
  display_name: _class
- id: title
  description: A human-readable name or title.
  display_name: title
- id: prose
  description: Permits multiple paragraphs, lists, tables etc.
  display_name: prose
- id: props
  description: A list of properties.
  display_name: props
  cardinality: multi
- id: links
  description: A list of links.
  display_name: links
  cardinality: multi
- id: name
  description: A textual label that uniquely identifies an attribute or semantic type.
  display_name: TermsAndConditionsPart_name
- id: parts
  description: A collection of parts.
  display_name: TermsAndConditionsPart_parts
  cardinality: multi
